---
 - hosts: local
    vars:
     remote_install_path: /etc/zabbix
     psk_name: {{ ansible_facts['nodename'] }}
    
 - tasks:

  - name: Copy across zabbix agent rpms
     copy:
      src: zabbix-agent-v4.rpm
      dest: /tmp/zabbix-agent-v4.rpm
      backup: no
          
  - name: Install the Zabbix Agent
    command: rpm -ivh zabbix-agent-v4.rpm
     args:
      chdir: /tmp
